config/routes.rb
Poodle::Application.routes.draw do

  get "static_pages/about"
  match '/about' => 'static_pages#about'
  get "static_pages/contact"
  match '/contact' => 'static_pages#contact'

  resources :waitlists

  resources :events do
    resources :drivers, :riders
  end

  match '/:id' => 'events#newuser', :as => :newuser
  match '/events/:id/newuser' => 'events#newuser', :as => :newuser_full

  match '/events/:id/:adminkey' => 'events#admin', :via => :get, :as => :admin
  match '/events/:id/admin' => 'events#adminsubmit', :via => :post, :as => :adminsubmit

  root :to => 'events#new'

end

app/models/waitlist.rb
class Waitlist < ActiveRecord::Base
  attr_accessible :event_id
  has_many :riders
  belongs_to :event 
end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  # GET /waitlists
  # GET /waitlists.json
  def index
    @waitlists = Waitlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @waitlists }
    end
  end

  # GET /waitlists/1
  # GET /waitlists/1.json
  def show
    @waitlist = Waitlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @waitlist }
    end
  end

  # GET /waitlists/new
  # GET /waitlists/new.json
  def new
    @waitlist = Waitlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @waitlist }
    end
  end

  # GET /waitlists/1/edit
  def edit
    @waitlist = Waitlist.find(params[:id])
  end

  # POST /waitlists
  # POST /waitlists.json
  def create
    @waitlist = Waitlist.new(params[:waitlist])

    respond_to do |format|
      if @waitlist.save
        format.html { redirect_to @waitlist, notice: 'Waitlist was successfully created.' }
        format.json { render json: @waitlist, status: :created, location: @waitlist }
      else
        format.html { render action: "new" }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /waitlists/1
  # PUT /waitlists/1.json
  def update
    @waitlist = Waitlist.find(params[:id])

    respond_to do |format|
      if @waitlist.update_attributes(params[:waitlist])
        format.html { redirect_to @waitlist, notice: 'Waitlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitlists/1
  # DELETE /waitlists/1.json
  def destroy
    @waitlist = Waitlist.find(params[:id])
    @waitlist.destroy

    respond_to do |format|
      format.html { redirect_to waitlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/waitlists/_form.html.erb
<%= form_for(@waitlist) do |f| %>
  <% if @waitlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waitlist.errors.count, "error") %> prohibited this waitlist from being saved:</h2>

      <ul>
      <% @waitlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waitlists/edit.html.erb
<h1>Editing waitlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @waitlist %> |
<%= link_to 'Back', waitlists_path %>

app/views/waitlists/index.html.erb
<h1>Listing waitlists</h1>

<table>
  <tr>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @waitlists.each do |waitlist| %>
  <tr>
    <td><%= waitlist.event_id %></td>
    <td><%= link_to 'Show', waitlist %></td>
    <td><%= link_to 'Edit', edit_waitlist_path(waitlist) %></td>
    <td><%= link_to 'Destroy', waitlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Waitlist', new_waitlist_path %>

app/views/waitlists/new.html.erb
<h1>New waitlist</h1>

<%= render 'form' %>

<%= link_to 'Back', waitlists_path %>

app/views/waitlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @waitlist.event_id %>
</p>


<%= link_to 'Edit', edit_waitlist_path(@waitlist) %> |
<%= link_to 'Back', waitlists_path %>