config/routes.rb
Poodle::Application.routes.draw do

  get "static_pages/about"
  match '/about' => 'static_pages#about'
  get "static_pages/contact"
  match '/contact' => 'static_pages#contact'

  resources :waitlists

  resources :events do
    resources :drivers, :riders
  end

  match '/:id' => 'events#newuser', :as => :newuser
  match '/events/:id/newuser' => 'events#newuser', :as => :newuser_full

  match '/events/:id/:adminkey' => 'events#admin', :via => :get, :as => :admin
  match '/events/:id/admin' => 'events#adminsubmit', :via => :post, :as => :adminsubmit

  root :to => 'events#new'

end

app/models/event.rb
class Event < ActiveRecord::Base
	obfuscate_id :spin => 75832164

  attr_accessible :name, :description, :time, :place, :admin, :email
  has_many :drivers 
  has_many :riders

  validates_presence_of :name, :admin, :email
  validates_format_of :email, with: /\A\S+@\S+\z/,  message: "Please use a valid email"
  # in future, use validates_email_format_of gem

  def private_email
  	email.first + "***" + email.match(/@.*/).to_s if email
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @drivers = Driver.where(event_id: @event)
    @riders = Rider.where(driver_id: @drivers)
    @waitlists = @event.riders.where(waitlist: true)
    #@riders = Rider.where(event_id: @event)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end

    # render :action => 'new'
  end

  def newuser
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # newuser.html.erb
      format.json {render json: @events}
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.admin_key = SecureRandom.hex(4)
    
    respond_to do |format|
      if @event.save

        UserMailer.event_confirmation(@event).deliver

        format.html { redirect_to @event, notice: "#{@event.admin}, your #{@event.name} was successfully created." }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def admin 
    @event = Event.find(params[:id])
    # @adminkey = Event.find(admin_key: params[:adminkey])

    respond_to do |format|
      if (params[:adminkey] == @event.admin_key)
        format.html { render action: "admin" }
      else
        #puts "routing errorrrrrr"
        raise ActionController::RoutingError.new('Not Found')
      end
    end
  end

  def adminsubmit
    @event = Event.find(params[:id])

    respond_to do |format|
      if (params[:admin_key] == @event.admin_key) 
        format.html { redirect_to "/events/#{params[:id]}/#{@event.admin_key}"}
      else
        format.html { render action: "edit" }
      end
    end
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_adminkey.html.erb
<%= form_tag adminsubmit_path do |f| %>
  
  <div class="field">
    <%= label_tag :admin_key %><br />
    <%= text_field_tag :admin_key %>
  </div>

  <div class="actions">
    <%= submit_tag "Enter" %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5, :class => "input-xxlarge" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_new.html.erb
<%= form_for(@event, url: {action: "create", anchor: "newEventForm"}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@event.errors.count, "error") %> prohibited this event from being created:</h6>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      <br />
    </div>
  <% end %>

  <style>
      /****  TEMPORARY STYLE FOR CURRENT VERSION OF THE FORM ****/
      #eventForm{
        width:80%;
        margin:0 auto;
      }

      .option-large{
        width: auto !important;
      }
  </style>

<div id="eventForm">
  <form>
    <div class="control-group">
      <div class="controls">
       <%= f.text_field :name, :placeholder => "Event Name", :class => "input-xxlarge" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.text_area :description, :placeholder => "Description", :rows => 5, :class => "input-xxlarge" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.datetime_select :time, {:default => 1.week.from_now, :start_year => DateTime.now.year, :ampm => true}, {:class => "option-large"} %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.text_field :admin, :placeholder => "Your Name", :class => "input-xxlarge" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.email_field :email, :placeholder => "Your Email", :class => "input-xxlarge" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Create Event", :class => 'btn btn-primary pull-right' %>
      </div>
    </div>
  </form>
</div>

<br/>
<h1>&nbsp;</h1>

<% end %>

app/views/events/admin.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<!-- <%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %> -->
<%= link_to 'Back', @event %> 

app/views/events/edit.html.erb
<h1>Editing event</h1>

<p>If you are the organizer for this event, check your email <%= @event.private_email %> for the admin key.</p>

<%= render :partial => '/events/adminkey' %>

<!-- <%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %> -->
<%= link_to 'Back', @event %> 

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %> | </td>
    <td><%= link_to 'Show', event %> | </td>
    <td><%= link_to 'Edit', edit_event_path(event) %> | </td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="jumbotron">
  <h2>Easy Carpooling</h2>
  <p class="lead">Ever tried organizing a carpool? It's a ton of work! Let us handle everything for you so you can focus on where you're going.</p>
  <p class="show row pull-right">
  	<%= link_to "Create an Event", '#', {:class => 'btn btn-large btn-success', :id => 'newEventButton'} %>

     <% ## new_event_path()  was the original address## %>


  	<!--<a class="btn btn-large btn-success" href="#">Create an Event</a>--></p>
</div>
  <br/><br/><br/>
  <hr class="show">

  <div id="newEventForm">
    <%= render :partial => '/events/new' %>
  </div>

<div class="row-fluid marketing">
  <div class="span6">
    <h4>No registration required</h4>
    <p>Create your event in seconds and make carpools the effortless part of your event.</p>
  </div>

  <div class="span6">
    <h4>Driver or Rider?</h4>
    <p>Just enter your name either as a driver or a rider and you're done!</p>
  </div>
</div>

<script>
$("#newEventButton").click(function () {
  $("#newEventForm").slideToggle();

  $('html, body').animate({
      scrollTop: $("#newEventForm").offset().top
  }, 2000);
});

<% unless @event.errors.any? %>

$('#newEventForm').hide();

<% end %>
</script>

app/views/events/newuser.html.erb
<div class="jumbotron">
  <h2>How will you contribute?</h2>
</div>

  <hr>

<div class="row-fluid marketing">
  <div class="span6">
    <%= link_to image_tag("wheel.png", :class => "img-polaroid"), new_event_driver_path(@event) %>
    <p align="center">I can drive!</p>
  </div>

  <div class="span6">
    <%= link_to image_tag("rider.png", :class => "img-polaroid"), new_event_rider_path(@event) %>
    <p align="center">I need a ride!</p>
  </div>
</div>

app/views/events/show.html.erb
<% if notice %>
    <div id="notice" class="alert alert-success"><%= notice %></div>
<% end %>

<h1 id="eventName" style="display:inline;"><%= @event.name %></h1>  
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %><br />
<br/>
<p>To sign up for this carpool, visit <%= link_to "#{newuser_url}", newuser_url %> &nbsp;<%= link_to image_tag("facebook_share.png", class: "facebook_icon", alt: "Facebook"), share_with_facebook_url({ url:  newuser_url,
                           title: "#{@event.name} Carpool Signup",
                           images: {0 => "#{root_url}assets/logo100x100.png"},
                           summary: "Carpoodle is the fastest and easy way to organize a Carpool with friends!" }),
                           target: "_blank" %>
                                   </p>
<br/><br/>
<dd><em><%= @event.description %></em></dd>
<br/>
<br/><br/>

<!-- Drivers -->
<ul>
    <% @drivers.each do |driver| %>
            <!-- Riders -->
            <ul class="driver" id="driver_<%= driver.id %>">
                <li class="headrider unmoveable"><%= driver.name %></li>
            <% @riders.each do |rider|   # Temporary solution, want to optimize later  %>
                <% if rider.driver_id == driver.id %>
                    <%= content_tag_for :li, rider, :"data-url" =>  event_rider_path(@event,rider) do %>
                        <%= rider.name %>
                    <% end %>
                <%  end %>
            <% end %>
            </ul>
    <% end %>
</ul>

<% if @drivers.empty? %>
    <em><% if @riders.empty? %>Your Carpoodle event is now ready! <%end%>Share the link above to have participants sign up to drive.</em><br/>
<% end %>

<div style="clear:both"></div>

<% unless @waitlists.empty? %>
<h6>Waitlisted participants without a ride</h6>
<% @waitlists.each do |waitlist| %>
    <ul>
        <li><%= waitlist.name %></li>
    </ul>
<% end %> 

<% end %>

<br />

<div style="display:block; width:100%; height:10px; clear:both;">&nbsp;</div>

<br/>

<script type="text/javascript">
    jQuery.ajaxSetup({ 
      'beforeSend': function(xhr) {xhr.setRequestHeader("Accept", "text/javascript")}
    })
    $(function() {
    $( ".driver" ).sortable({
      items: "li:not(.unmoveable)",
      connectWith: ".driver",
      placeholder: "ghostRider",
      update: function(){
        $.post($(this).data("url"), $(this).parent(".driver").attr("id"))
        }
      }
    ).disableSelection();
    })

    $(document).ready(function () {
        $('#notice').delay(2000).fadeOut('slow');
    })
</script>