config/routes.rb
Poodle::Application.routes.draw do

  get "static_pages/about"
  match '/about' => 'static_pages#about'
  get "static_pages/contact"
  match '/contact' => 'static_pages#contact'

  resources :waitlists

  resources :events do
    resources :drivers, :riders
  end

  match '/:id' => 'events#newuser', :as => :newuser
  match '/events/:id/newuser' => 'events#newuser', :as => :newuser_full

  match '/events/:id/:adminkey' => 'events#admin', :via => :get, :as => :admin
  match '/events/:id/admin' => 'events#adminsubmit', :via => :post, :as => :adminsubmit

  root :to => 'events#new'

end

app/models/rider.rb
class Rider < ActiveRecord::Base
    obfuscate_id :spin => 69686322

  attr_accessible :driver_id, :name, :event_id, :telephone, :waitlist
  belongs_to :driver 
  belongs_to :event

  validates_presence_of :name

  before_save :set_waitlist
  
  def set_waitlist
  	if self.driver_id.blank? then
  		self.waitlist ||= 1
  	else
  		self.waitlist ||= 0
  	end
  end

  def update_waitlist
  	if self.driver_id.blank? then
  		update_attribute :waitlist, 1
  	else
  		update_attribute :waitlist, 0
  	end
  end

  def update_driver(driver_id)
  	update_attribute :driver_id, driver_id
  end

end

app/controllers/riders_controller.rb
class RidersController < ApplicationController

  before_filter :get_event, :except => [:index]
  before_filter :get_opendriver, :only => [:new, :create]

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @riders }
    end
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
    @rider = Rider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rider }
    end
  end

  # GET /riders/new
  # GET /riders/new.json
  def new
    #@event = Event.find(params[:id])
    #@rider = Rider.new
    @rider = Rider.new(:event_id => params[:event_id])
    #@drivers = @event.drivers

    #@rider.driver_id = @opendriver.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rider }
    end
  end

  # GET /riders/1/edit
  def edit
    @rider = @event.riders.find(params[:id])
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = @event.riders.new(params[:rider])
    @rider.driver_id = @opendriver.id if @opendriver

    respond_to do |format|
      if @rider.save
        @opendriver.update_full if @opendriver
        format.html { redirect_to [@event, @rider], notice: 'Rider was successfully created.' }
        format.json { render json: @rider, status: :created, location: @rider }
      else
        format.html { render action: "new" }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /riders/1
  # PUT /riders/1.json
  def update
    #@rider = Rider.find(params[:id])
    @rider = @event.riders.find(params[:id])

    respond_to do |format|
      if @rider.update_attributes(params[:rider])
        format.html { redirect_to [@event, @rider], notice: 'Rider was successfully updated.' }
        format.json { head :no_content }
        format.js { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider = Rider.find(params[:id])
    @rider.destroy

    respond_to do |format|
      format.html { redirect_to riders_url }
      format.json { head :no_content }
    end
  end

  def get_event
    @event = Event.find(params[:event_id])
  end

  def get_opendriver
    @opendriver = @event.drivers.find_by_full(false);
  end

end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/riders/_form.html.erb
<%= form_for [@event, @rider] do |f| %>
  <% if @rider.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@rider.errors.count, "error") %> prohibited this rider from being saved:</h6>

      <ul>
      <% @rider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.telephone_field :telephone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/riders/edit.html.erb
<h1>Editing rider</h1>

<%= render 'form' %>

<%= link_to 'Back', event_rider_path(@event) %>

app/views/riders/index.html.erb
<h1>Listing riders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Driver</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @riders.each do |rider| %>
  <tr>
    <td><%= rider.name %></td>
    <td><%= rider.driver_id %></td>
    <td><%= link_to 'Show', rider %></td>
    <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
    <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rider', new_rider_path %>

app/views/riders/new.html.erb
<h1>New rider</h1>

<%= render 'form' %>

<%= link_to 'Back', newuser_path(@event) %>

<script type="text/javascript">
$(document).ready(function() {
	$('input#rider_telephone').mask("(999) 999-9999");
});	
</script>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Rider info</h2><br/>
<p>
  <b>Name:</b>
  <%= @rider.name %>
</p>

<p>
  <b>Event:</b>
  <%= @rider.event.name %>
</p>

<p>
  <b>Telephone:</b>
  <%= @rider.telephone %>
</p>

<br/>
<% if @rider.waitlist == true %>
	<p> You are currently on the waitlist, you will be assigned a driver as soon as possible.  </p>
<% else %>
	<p> You currently are assigned to a driver </p>
<% end %>
<br/>

<%= link_to 'Back', @event %>