config/routes.rb
Poodle::Application.routes.draw do

  get "static_pages/about"
  match '/about' => 'static_pages#about'
  get "static_pages/contact"
  match '/contact' => 'static_pages#contact'

  resources :waitlists

  resources :events do
    resources :drivers, :riders
  end

  match '/:id' => 'events#newuser', :as => :newuser
  match '/events/:id/newuser' => 'events#newuser', :as => :newuser_full

  match '/events/:id/:adminkey' => 'events#admin', :via => :get, :as => :admin
  match '/events/:id/admin' => 'events#adminsubmit', :via => :post, :as => :adminsubmit

  root :to => 'events#new'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
	obfuscate_id :spin => 50415581

  attr_accessible :event_id, :name, :spots, :telephone, :full
  has_many :riders
  belongs_to :event 

  validates_presence_of :name, :spots
  validates_numericality_of :spots, only_integer: true, greater_than_or_equal_to: 1

  before_save :set_full
	def set_full
		if (self.spots > self.riders.size) 
			self.full ||= 0
		else
			self.full ||= 1
		end
	end

	def update_full
		if (self.spots > self.riders.size) 
			update_attribute :full, 0
		else
			update_attribute :full, 1
		end
	end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  before_filter :get_event, :except => [:index]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drivers }
    end
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    @driver = Driver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/new
  # GET /drivers/new.json
  def new
    @driver = Driver.new(:event_id => params[:event_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/1/edit
  def edit
    #@driver = Driver.find(params[:id])
    @driver = @event.drivers.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = @event.drivers.new(params[:driver])

    respond_to do |format|
      if @driver.save

        for i in 1..@driver.spots do
          @waitlistrider = @event.riders.find_by_waitlist(true)
          @waitlistrider.update_driver(@driver.id) if @waitlistrider
          @waitlistrider.update_waitlist if @waitlistrider
        end

        @driver.update_full

        format.html { redirect_to [@event, @driver], notice: 'Driver was successfully created.' }
        format.json { render json: @driver, status: :created, location: @driver }
      else
        format.html { render action: "new" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drivers/1
  # PUT /drivers/1.json
  def update
    #@driver = Driver.find(params[:id])
    @driver = @event.drivers.find(params[:id])

    respond_to do |format|
      if @driver.update_attributes(params[:driver])
        format.html { redirect_to [@event, @driver], notice: 'Driver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url }
      format.json { head :no_content }
    end
  end

  def get_event
    @event = Event.find(params[:event_id])
  end

end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for [@event, @driver] do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h6>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :spots, "Available Spots (not including you)" %><br />
    <%= f.number_field :spots %>
  </div>
    <div class="field">
    <%= f.label :telephone %><br />
    <%= f.telephone_field :telephone %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render 'form' %>

<%= link_to 'Back', event_driver_path(@event) %>

app/views/drivers/index.html.erb
<h1>Listing drivers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Spots</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drivers.each do |driver| %>
  <tr>
    <td><%= driver.name %></td>
    <td><%= driver.spots %></td>
    <td><%= driver.event_id %></td>
    <td><%= link_to 'Show', driver %></td>
    <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
    <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render 'form' %>

<%= link_to 'Back', newuser_path(@event) %>


<script type="text/javascript">
$(document).ready(function() {
	$('input#driver_telephone').mask("(999) 999-9999");
});	
</script>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Driver info</h2><br/>
<p>
  <b>Name:</b>
  <%= @driver.name %>
</p>

<p>
  <b>Spots:</b>
  <%= @driver.riders.size %> out of <%= @driver.spots %> spots are occupied
</p>

<p>
  <b>Event:</b>
  <%= @event.name %>
</p>

<p>
  <b>Telephone:</b>
  <%= @driver.telephone %>
</p>

<%= link_to 'Back', @event %>